services:
  macos:
    image: dockurr/macos
    container_name: songloft-lynx-macos
    environment:
      VERSION: "15"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      DISK_SIZE: "256G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
      - 2222:22
    dns:
      - 30.30.30.30
      - 223.5.5.5
      - 8.8.8.8
    volumes:
      - macos-storage:/storage
    stop_grace_period: 2m
    restart: unless-stopped

volumes:
  macos-storage:
