export { PluginManagerPage } from './pages/PluginManagerPage.js'
export { PluginRegistryPage } from './pages/PluginRegistryPage.js'
export { GithubDiscoveryPage } from './pages/GithubDiscoveryPage.js'
export { PluginWebViewPage } from './pages/PluginWebViewPage.js'
export { TabConfigPage } from './pages/TabConfigPage.js'
export { PluginGrid } from './widgets/PluginGrid.js'
export { PluginTabIcon } from './widgets/PluginTabIcon.js'
export { useShellNavTabs } from './data/tab-config.js'
export type { PluginTabEntry, TabConfig, ShellNavTabs } from './data/tab-config.js'
export { handlePluginHostCall } from './domain/plugin-host-dispatch.js'
export type { HostCallRequest, HostCallResult, PluginHostContext } from './domain/plugin-host-dispatch.js'
